### PR TITLE
Output results as CSV

### PR DESCRIPTION
**Pull request by nvuillam**
--output csv,console(default)
--outputfile: path of CSV file, or default current directory + reports/flow-scanner-results.csv
Fixes https://github.com/Lightning-Flow-Scanner/lightning-flow-scanner-sfdx/issues/74

Example output: 
image

### CODE REVIEW

**Comment by nvuillam** [comment]
@RubenHalman note: to merge after https://github.com/Lightning-Flow-Scanner/lightning-flow-scanner-sfdx/pull/80 to see the real diff :)

**Comment by RubenHalman** [comment]
@nvuillam This seems really great and much needed functionality. My hesitance in merging this PR is that we will at least momentarily create two different ways of generating a CSV. I think it is important for the maintenance of the overall project that we have one single solution and if possible, this would be implemented in the core module itself so that it can be exposed to the sfdx plug in and vs code extension. Therefore I want to investigate if I can implement exactly what you have done here in the visual studio code extension. If so, we can merge this directly. Please bear with me a bit:)

**Comment by nvuillam** [comment]
Most of users will need CSVs from CICD jobs... so the sfdx plugin should be able to generate it ^^

**Comment by RubenHalman** [comment]
we are fully aligned on that, however, as I mentioned in the original issue, the csv formatting should be implemented in the core module. I can definitely use this code and if you want please do go ahead in starting a pr on the core

**Pull request closed without merging**
