### PR TITLE
test: enable testing, and automate execution of tests when PR is opened

### PR DESCRIPTION
**Pull request by k-capehart**
Tests were not properly running when I ran `npm run test` so I made a few updates to make it match how it works in `core`. ~~This includes adding a workflow to automatically run the tests when a PR is opened.~~

This should enable more unit tests to be created specifically for the sfdx plugin.

### CODE REVIEW

**Comment by k-capehart** [comment]
Oops, I see @nvuillam already submitted a PR with a test workflow. I removed that part so it doesn't conflict but the other changes are still needed in order to run the tests successfully.

**Comment by k-capehart** [comment]
@junners FYI

**Comment by nvuillam** [comment]
@k-capehart it's not a merged PR, mostly because the testing did not work, so if your PR solves it, that's great :)

**Review by junners — APPROVED** [review]
Looks good to me!

**Pull request merged**
